// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReplicationService.proto

package org.ptm.kvservice.proto;

public final class ReplicationServiceOuterClass {
  private ReplicationServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Updates_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Updates_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SequenceNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SequenceNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ReplicationService.proto\022\005proto\"2\n\007Upd" +
      "ates\022\026\n\016sequenceNumber\030\001 \001(\003\022\017\n\007updates\030" +
      "\002 \001(\014\"(\n\016SequenceNumber\022\026\n\016sequenceNumbe" +
      "r\030\001 \001(\0032E\n\022ReplicationService\022/\n\004sync\022\025." +
      "proto.SequenceNumber\032\016.proto.Updates0\001B!" +
      "\n\035com.coccoc.bi.kvservice.protoP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_Updates_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Updates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Updates_descriptor,
        new java.lang.String[] { "SequenceNumber", "Updates", });
    internal_static_proto_SequenceNumber_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_SequenceNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SequenceNumber_descriptor,
        new java.lang.String[] { "SequenceNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
