// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReplicationService.proto

package org.ptm.kvservice.proto;

public interface SequenceNumberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.SequenceNumber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sequenceNumber = 1;</code>
   * @return The sequenceNumber.
   */
  long getSequenceNumber();
}
