// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReplicationService.proto

package org.ptm.kvservice.proto;

public interface UpdatesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Updates)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sequenceNumber = 1;</code>
   * @return The sequenceNumber.
   */
  long getSequenceNumber();

  /**
   * <code>bytes updates = 2;</code>
   * @return The updates.
   */
  com.google.protobuf.ByteString getUpdates();
}
